name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10 
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2 
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install coverage
        run: |
          pip install coverage
      - name: Generate report
        run: |
          coverage run -m pytest -vs
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
      
